### ISSUE TITLE
The functions `validate_utf8_basic` should not be labeled unsafe

### ISSUE THREAD

**Issue by ArniDagur** [rusticstuff/simdutf8#27]
We already assume that calling `validate_utf8_basic` is safe, since it's called within `from_utf8` and `from_utf8_mut` which are labelled safe. Thus, it doesn't make any sense for `validate_utf8_basic` to be labelled an unsafe API.

**Comment by hkratz** [comment]
@ArniDagur: Which `validate_utf8_basic()` do you mean? The public ones in [`simdutf8::{basic,compat}::imp`](https://docs.rs/simdutf8/0.1.1/simdutf8/basic/imp/x86/avx2/fn.validate_utf8.html) redirect down to the actual SIMD implementation methods which have to be unsafe because they have `#[target_feature(enable = "...")]` attributes.

**Comment by ArniDagur** [comment]
I'm talking about the public ones. There is no way to call `simdutf8::basic::imp::x86::avx2::validate_utf8`, for example, unless the target CPU has `avx2`. Having `#[target_feature(enable = "...")]` is what makes the function safe.

**Comment by ArniDagur** [comment]
Actually, no. I'm wrong. I was confusing `#![cfg(target_feature = "avx2")]` and `#[target_feature(enable = "avx2")]`.
